#!/usr/bin/env node
// NOTE: This script must be implemented to run in node without any external
// dependencies.
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Only run the move-winpty-binaries script if it is built. This covers the
// case when a local `npm install` is being done during development.
let moveWinPtyBinariesScript = path.resolve(
  __dirname,
  '..',
  'dist',
  'scripts',
  'move-winpty-binaries.js'
);
if (fs.existsSync(moveWinPtyBinariesScript)) {
  spawnSync(
    process.execPath,
    [
      moveWinPtyBinariesScript
    ]
  );
}
